const rightArrow = document.getElementById("buttonRight");
const leftArrow = document.getElementById("buttonLeft");
const image = document.getElementById("picture");

var pictures = [
    "Mandelbrot_image6.jpeg", 
    "Mandelbrot_image5.png", 
    "Mandelbrot_image1.png", 
    "Mandelbrot_image7.jpeg",
    "Game_of_Life_image4.png",  
    "L_System_image3.png", 
    "L_System_image2.png", 
    "graph.jpeg",
    "terrain.jpeg", 
    "maze.jpeg",
    "tetris.png",
    "snake.png"
];

var titles = [
    "A portion of the Mandelbrot set. Generated by my program that finds interesting spots on the Mandelbrot Set, textured for extra flavor. Written in C, output: .tiff file",
    "A portion of the Mandelbrot set. Viewed from my Mandelbrot Viewer Github page. Written in javascript.",
    "A portion of the Mandelbrot set; a Julia set formation in close proximity to a \'Minibrot\'. Viewed and calculated from my Mandelbrot Viewer Github page. Written in javascript.",
    "A portion of the Mandelbrot set. Generated by my program that finds interesting spots on the Mandelbrot Set, textured for extra flavor. Written in C, output: .tiff file",
    "Conway's Game of Life: double glider gun. Viewed and calculated from my Game of Life Github page. Written in javascript.",
    "Recursive L-system. Viewed and calculated from my L-System Github page. Written in javascript.",
    "Recursive L-system tree. Viewed and calculated from my L-System Github page. Written in javascript.",
    "Newton fractal of some complex function (I don't remember, this was a while ago). Written in C, output: .tiff file",
    "Randomly generated terrain with crater impacts. Written in C.",
    "Randomly generated Maze. From one of the several maze generation programs that I have made. Written in C.",
    "Command Line Tetris recreation. Written in C.",
    "Command Line Snake recreation. Written in C."
]

var current = 0;
var len = pictures.length;

rightArrow.addEventListener("click", function(event) {
    current = (current + 1)%len;
    image.src = pictures[current];
    image.title = titles[current];
});

leftArrow.addEventListener("click", function(event) {
    current = (current + len - 1)%len;
    image.src = pictures[current];
    image.title = titles[current];
});
